### ISSUE TITLE
install script hardcodes home directory

### ISSUE THREAD

**Issue by jrobeson** [oh-my-fish/oh-my-fish#136]
I'm not sure if this is intended or not, but i ended up with

```bash
set -gx OMF_PATH /home/johnny/.local/share/omf
#set -gx OMF_CONFIG /home/johnny/.config/omf
```

when I expected:
```bash
set -gx OMF_PATH $HOME/.local/share/omf
#set -gx OMF_CONFIG $HOME/.config/omf
````

**Comment by jrobeson** [comment]
maybe we'd even want to use `$XDG_CONFIG_HOME` and `XDG_DATA_HOME` here and then before that, set them if aren't set.

**Comment by derekstavis** [comment]
I don't remember if previous bash installer hardcoded home directories too. If it used `HOME`, if, there was a mistake when rewriting the installer in fish.

>maybe we'd even want to use $XDG_CONFIG_HOME and XDG_DATA_HOME here and then before that, set them if aren't set.

Prior to #77 `XDG_CONFIG_HOME` and `XDG_DATA_HOME` was resolved at install time and then used literally in `config.fish`. I preferred over keeping the previous behaviour instead of messing with XDG in init file. The idea is to migrate to XDG, as per #79 `OMF_CONFIG` uses XDG when it isn't specified in `config.fish` (that's why it's commented by default).

I don't know wether we should set this variables when they are not set. XDG is a opt-in in distributions like Arch Linux, so the user may not be expecting for such behaviour.

**Comment by jrobeson** [comment]
I've never used oh-my-fish before, so I am not familiar with how things were before

**Comment by bpinto** [comment]
I believe `$HOME` was added to the init file before the changes.

**Comment by bpinto** [comment]
@jrobeson could you work on a PR to solve this?

**Comment by coderstephen** [comment]
This has now been fixed in the latest version of the installer!
