### ISSUE TITLE
[Idea] [Suggestion] Support  offline installation

### ISSUE THREAD

**Issue by redstar9451** [oh-my-fish/oh-my-fish#167]
I work on a redhat enterprise 6.1 server, the server is offline.
The others guys in my office work on it too.

we have installed the fish by rpm package,  but we can't install omf automatic.

i had installed omf by hand, but i am not sure whether there are something wrong.

i think maybe omf can support the situation like ours, how about it ?

**Comment by bpinto** [comment]
I think I understood, but just to be sure, what do you mean by offline installation?

**Comment by bpinto** [comment]
ping @redstar9451

**Comment by redstar9451** [comment]
I download the zip file , and i run the command "fish install" under the directory "omf_base_directory"/bin, It does not work , because our linux server is not connected to the internet( this is what the "offline" mean) 

i modify the code such as "git clone" and "git upstream" ,  the installation(through the command "fish install") works , but i don't know whether there are something wrong.

**Comment by derekstavis** [comment]
I like the idea. What about something like this:

```fish
fish install --offline
```

For upgrading the framework:

```fish
fish install --offline --upgrade
```

**Comment by bpinto** [comment]
I'd focus on installing fish offline first and then thinking about packages. As packages are git repositories, you can just copy them there if you already have them offline.

**Comment by redstar9451** [comment]
@derekstavis yes, that's what I mean.

**Comment by bucaran** [comment]
@redstar9451 But in order to install a package you need to download it first right? Then you want the ability to uninstall and reinstall anytime. Is that what you mean maybe?

**Comment by bucaran** [comment]
@redstar9451 But in order to install a package you need to download it first right? So, you want the ability to uninstall and reinstall anytime. Correct?

EDIT: OK, I get it now. If you need this functionality, check out Fisherman, it has a builtin cache mechanism that may be what you are looking for.

**Comment by bucaran** [comment]
@redstar9451 But in order to install a package you need to download it first right? So, you want the ability to uninstall and reinstall anytime. Correct?

EDIT: OK, I get it now. If you need this functionality, check out Fisherman, it has a builtin cache mechanism that may be what you are looking for.

**Comment by coderstephen** [comment]
This has now been implemented in #361.
