### ISSUE TITLE
please help implement sudo plugin of zsh in fish

### ISSUE THREAD

**Issue by thecotne** [oh-my-fish/oh-my-fish#183]
this plugin https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/sudo/sudo.plugin.zsh

i can't find out how to bind to esc esc or change LBUFFER

**Comment by bpinto** [comment]
I don't know much about binding, perhaps @derekstavis have an idea?

**Comment by oranja** [comment]
Hi, @thecotne. Any progress?
This looked interesting, so I decided to try to dig into it.

As for the key-bindings, when you say "esc esc", do you mean pressing `Esc` twice? or escape-sequence+`Esc`? Perhaps these two should work the same (after all, `Esc` should send the escape-sequence prefix :confused:), but I only managed to make it work for escape-sequence+`Esc` (i.e. `Alt`+`Esc`). On the other hand, I'm running Fish inside Tmux inside Byobu inside Konsole. Any one of these might intercept my `Esc` key strokes and affect the final behavior.

For changing the current command line buffer, you can use Fish's [`commandline`].
I managed to make this work:
```fish
bind \e\e 'begin; set -l buf (commandline); commandline -r "sudo "$buf; end'
```
So that pressing `Alt`+`Esc` puts "sudo " at the beginning of the current command line.

I don't know if LBUFFER exists in fish, but you can recreate it with `commandline -c`, so implementing the rest of the function shouldn't be a problem.

[`commandline`]: http://fishshell.com/docs/current/commands.html#commandline

**Comment by bpinto** [comment]
🎉

**Comment by thecotne** [comment]
@bpinto thx for your replay

> As for the key-bindings, when you say "esc esc", do you mean pressing Esc twice? or escape-sequence+Esc?

i mean pressing Esc twice

i have switched back to zsh only for this shortcut

i will give fish-shell another try in future

**Comment by bpinto** [comment]
@oranja @thecotne 

It would be nice to convert it into a plugin. What do you think? Would like to work on it?

**Comment by oranja** [comment]
https://github.com/oranja/omf-plugin-sudope

**Comment by bpinto** [comment]
That is great! Submit a PR adding it to the db?

**Comment by oranja** [comment]
I knew there was some PR I had to do, just too excited to actually do it lol
#204

**Comment by thecotne** [comment]
@oranja looks good :+1: 

it will be better if it worked with "pressing Esc twice" (how it works in oh my zsh)

**Comment by oranja** [comment]
If I understand correctly, this is a known problem with Fish.
I've bumped the issue (https://github.com/fish-shell/fish-shell/issues/1356) and let's see what happens.
Sadly, ncurses and terminals are beyond my expertise.

**Comment by oranja** [comment]
@thecotne, it seems like things are moving in Fish and I thought I'd bring you (and anyone interested) up to speed.
So now besides progress in fish-shell/fish-shell#1356, there's also a pull request (fish-shell/fish-shell#2630) by @krader1961. I did my best to help speed it by building and testing Fish locally with the patch that he proposed. I'm happy to let you know that after applying the patch, `Esc`,`Esc` worked as a sequence for bind (only with a small delay). However, they are still waiting for more feedback before deciding if to merge.
As for the Fish port of the sudo plugin, I spent some more time with it. It works (`Ctrl`+`s` is the default shortcut though, not double `Esc`), at least on Linux, and you can [grab it](https://github.com/oranja/omf-plugin-sudope) from my repo manually. The setback now is that I have to consult with the people here and over at fish-shell before I propose to add it to the plugins recognized by OMF.

**Comment by oranja** [comment]
@thecotne and anyone else interested.
There are by now at least two working solutions to the popular demand for a `sudo` shortcut.

If you like the `bash` way: https://github.com/oh-my-fish/plugin-bang-bang
*"!! on command line will be replaced by last command issued."*
`omf install bang-bang`

If you like the `zsh` way: https://github.com/oranja/omf-plugin-sudope
*"Press Ctrl+s once to add 'sudo' (normal behaviour), press it twice to remove it from the beginning of the line.*"
`omf install https://github.com/oranja/omf-plugin-sudope.git`
(I need to ask again to have it in the package database)
If you use Fish 2.3 (or above), you can change `sudope_sequence` in `key_bindings.fish` to '\e\e' and then `<Esc>,<Esc>` will get you the same behavior as in oh-my-zsh.

Enjoy.
(And this issue can be closed)
