### ISSUE TITLE
The preview image for the nelsonjchen theme at the theme gallery doesn't appear to be working.

### ISSUE THREAD

**Issue by nelsonjchen** [oh-my-fish/oh-my-fish#216]
https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md

Do I need to change something in my README.md to get the script that generates that file working or is this a bug in the script? I noticed there was some attempt at namespacing as the last commit at the time of this report.

**Comment by bpinto** [comment]
It's a bug on the script. It is happening because you are showing a screenshot that is inside git using a partial URL. I'd advise to not add a screenshot to the git repository, it's going to unnecessarily increase the git repo size. I'd upload the screenshot to a github issue and link to it instead.

**Comment by nelsonjchen** [comment]
I have done just that then. Please update the gallery.
