### ISSUE TITLE
Batman theme does not work.

### ISSUE THREAD

**Issue by mathiasvr** [oh-my-fish/oh-my-fish#249]
Hi the batman theme does not seem to work, and since issues are disabled on its repository i am posting this here.

A list of errors about unknown commands (functions) are displayed such as this:

    fish: Unknown command 'dim'
    ~/.local/share/omf/themes/batman/fish_right_prompt.fish (line 1): dim
                                                                  ^
    in command substitution
	    called on line 16 of file ~/.local/share/omf/themes/batman/fish_right_prompt.fish

    ...

The declared functions are not shared between files, but merging everything into a single file solves the problem. I suppose this is due to some changes in omf?

I am running `Oh My Fish! 1.0.0` on `Mac OS X 10.11.2`

**Comment by derekstavis** [comment]
Hey! Thanks for reporting!! This is about how the theme was poorly designed. The original author assumed that adding those functions to `fish_greeting.fish` would work, because `fish_greeting` is the first function to be called. Unfortunately, for the ones who disabled greeting message it's not true. I will give a look at what can be done with the theme to make it work (and not pollute with that functions).

**Comment by mathiasvr** [comment]
My bad, I don't know why the greeting would have been disabled, but it works now. I think it might have something to do with a fish_prompt.fish function which which was in my local functions? Unless you have any suggestions, you could probably just close the issue.

**Comment by derekstavis** [comment]
I will close it here, but we should open the issue in the batman repo, as it's a known issue. I will be re-enabling issues there and open it. Thanks for reporting here :+1:
