### ISSUE TITLE
Fixing file behaviors

### ISSUE THREAD

**Issue by michaelperrygoodman** [oh-my-fish/oh-my-fish#267]
Hi. Apologies for how this comes off as I just lost hours of work because of the 'omf destroy' command removing files it had no business touching. Here's the setup (OSX):

I want to contain my customized fish stuff in my Google Drive folder, as well as having it exist as a submodule to my dotfiles repo. I am also trying to run OMF. So I (perhaps foolishly) pointed my 'custom OMF configuration path' to the standard '$HOME/.config/fish' directory. This dir is actually a symlink to my GDrive folder with the same name and structure. It contains a functions/ directory with aliases.fish, fish_prompt.fish and a few other files I source (because I guess I don't really understand how this folder is supposed to be autoloaded by OMF).

Some of the files were not loading correctly and I could not understand why, so I decided to destroy and reinstall OMF. I realize it makes backups when you do an initial install, which I already was not fond of since I do not think it should be touching anything besides the config.fish. And again foolishly removing these backups (specifically for config.fish and functions/fish_prompt.fish). Finally, when I performed 'omf destroy' it did precisely what that command implies and deleted both of these files. It also, however, somehow managed to revert the functions/aliases.fish file to its original state, which destroyed quite a lot of work I had been doing.

So, I guess what I'm wondering here is if there isn't some way to make this "custom" settings folder independent entirely of OMF so it doesn't wreck my work. Perhaps some safeguard checking when working with custom folders? And instead of flat out deleting files, just leaving them alone? I want my custom configurations and functions to work along side OMF, not inside of it, or being managed by it in any way. Am I missing some obvious part of how fish and OMF work? I know I blundered this quite a bit by not taking steps to make sure my data wouldn't be destroyed, but I didn't quite expect this. Thanks for any help.

**Comment by bobthecow** [comment]
It _should_ only remove  `$OMF_PATH`, which is the core OMF library, and restore your backed up files to `~/.config/fish/config.fish` and `~/.config/fish/functions/fish_prompt.fish`.

The latter is destructive, though, and it should probably make a fresh backup before replacing them with your older original files, in case you've customized them after installing OMF.

**Comment by oranja** [comment]
Hi Michael,

First let's address your data: I am pretty certain that GDrive both keeps file versions and has a trash can that you can restore your files from before they're permanently lost. Older versions and deleted files are kept for 30 days, from a quick check.
I recently restored a folder with some 3000 files that was deleted in one moment due to a mistake with a synching software.

As for `omf destroy`, let's break it down to parts:

1. As @bobthecow said, some of what you're describing makes no sense with the current version of `omf`. It should not mess with **$OMF_CONFIG** or your `aliases.fish`. I don't know what was before the current version, but there is nothing we can possibly do to fix out-of-date installations.

2. There is no reasonable way to make `fish` aware of `omf` without writing into your personal **config.fish**, and if it messes with your files on install, most people will expect it to put everything back to place after it's gone. With that being said, perhaps instead of keeping ancient backups, what OMF can do is to:
(a) On install, move **config.fish** to **before.config.fish** or something like that, and create an empty **after.config.fish**, and
(b) in the new **config.fish** put a warning not to edit the file directly, source **before.config.fish**, omf's **init.fish** and **after.config.fish**,
(c) On `destroy`, it's possible to simply `cat before.config.fish after.config.fish > config.fish` and `rm -f {before,after}.config.fish`

3. For `fish_prompt.fish` perhaps we can use the same trick we use in `better-init` for key-bindings. Rename the old function in-memory and source another from within **$OMF_CONFIG**. Then again, if you point `$OMF_CONFIG` to your fish directory, it's hard to promise no clashes. They are meant to be separate folders. OMF doesn't change the way that your custom functions in `.config/fish/functions` are loaded. IIRC, they only get lower precedence in the case of a conflict.

4. We agree at least that removing the entire **$OMF_PATH** directory makes sense?

**Comment by michaelperrygoodman** [comment]
Thank you very much for the insight. I obviously have more homework to do but this has been a helpful exercise in understanding how OMF behaves and how I could improve my habits.

#4, to me, is of course reasonable since it contains all of OMF.

For the `config.fish` itself, maybe just appending to the file of clobbering it? It seemed strange to me that it would do that. I had it opened in my editor when it did it the first time and thankfully I just Cmd+Z. I still don't really think the `fish_prompt.fish` in the custom directory should ever be touched at all though.

I think the most confusing thing was the aliases.fish issue. I'm going to chalk that up as anomaly for now but maybe I can try to replicate that again another day.

**Comment by oranja** [comment]
2. (continued) I have to agree with you about `config.fish`. I had in mind that the installer only prepends the OMF initialization calls and I'm surprised (like you were at the time) to see that it works by replacing the file entirely. This is definitely something I'd like to see changed.

3. (continued) When I come to think of it again, I recall that using the "real" `fish_prompt.fish` is required to keep compatibility with the `fish_config` utility. So it's supposedly a trade-off, but one that usually doesn't hurt so much.

Let us know if the aliases.fish problem returns.

_I'd like to keep this open as it contains several possible improvements to the installer._

**Comment by coderstephen** [comment]
Most of these improvement ideas for the installer have been incorporated in #361.
