### ISSUE TITLE
Plugin submission procedure

### ISSUE THREAD

**Issue by Shadowigor** [oh-my-fish/oh-my-fish#297]
Hi

I'd like to make a pull request for a plugin I wrote, but there is something that confuses me. The doc tells me to run 'omf submit pkg/my-plugin .../my-plugin.git'. If I understand that right, that assumes that the plugin would be part of the oh-my-fish user. So would my plugin get integrated to the oh-my-fish user, do I have to change that to my own URL or am I completely wrong?

Thanks

**Comment by oranja** [comment]
Hello @Shadowigor,

`omf submit` is indeed a bit tricky for people outside the oh-my-fish organization.
It simply adds the URL of your plugin to the **db** folder in your local OMF repository. The **db** folder is OMF's package index. Later you need to create a Pull Request so that the plugin can be reviewed and accepted. But here is the hurdle - most of us don't have push permissions to OMF's repository here on github.
So in order to create a PR, you need to fork the OMF repository (which you already have). Then you can either make the same simple changes to the **db** folder in your fork, or you can add your fork as a second _remote_ , or change the push URL for your first remote (usually called **origin**). Once you push the changes to your fork, opening a pull request to the main OMF repo is easy.

Now to answer your true question: The plugin itself doesn't have to be under the oh-my-fish organization. Your submit command should look like this:
```fish
omf submit myplugin https://github.com/Shadowigor/plugin-myplugin.git
```
(Where you need to replace both 'myplugin' with your plugin's name)

If you need further help with any of these steps, let us know.

**Comment by Shadowigor** [comment]
Thanks, I thought that it's done that way but I wasn't sure.
