### ISSUE TITLE
omf install removes symlinked bundle

### ISSUE THREAD

**Issue by andrewrynhard** [oh-my-fish/oh-my-fish#303]
I use a dotfile manager that symlinks `$OMF_CONFIG/bundle`. When I run `omf install <plugin-name>` the link gets replaced by a file. Many dotfile managers use symlinks. It would be useful to change this behavior.

**Comment by oranja** [comment]
Thank you for this vital feedback.

My estimate is that the culprit lies in [omf.bundle.add](https://github.com/oh-my-fish/oh-my-fish/blob/master/pkg/omf/functions/bundle/omf.bundle.add.fish#L13) (the `sort` call).
This brings the question: Do we really need the bundle file sorted at all times? (I never understood the motive)

@andrewrynhard: we'll try to get to it soon, but feel free to suggest a fix for this in a PR yourself.

**Comment by andrewrynhard** [comment]
Thanks! I will try to take a stab at it.
