### ISSUE TITLE
Deprecated use of function `available` in powerline plugin

### ISSUE THREAD

**Issue by temsa** [oh-my-fish/oh-my-fish#326]
Using Ubuntu 16.04 and the default fish version 2.2.0 and the "powerline" plugin (which is great BTW !), I've got on each login these warnings displayed :
```
warning: function available is deprecated and will be removed soon.
called on line 2 of file ~/.local/share/omf/pkg/powerline/init.fish
warning: function available is deprecated and will be removed soon.
called on line 9 of file ~/.local/share/omf/pkg/powerline/init.fish
```

See also the bug, including the workaround, at https://github.com/iamruinous/plugin-powerline/issues/2

**Comment by oranja** [comment]
Just to clarify: there is nothing we can (read: want) to do about this error.
The `available` function was discarded because it was a useless wrap around the idiomatic `type -q`. The deprecation message is there exactly so that users can find these pieces of outdated code and report to maintainers.

I personally suggest that you provide a PR to iamruinous/plugin-powerline according to @Ramblurr's suggested fix. It will make it easier for @iamruinous, if he is short on time. If time passes and there is no comment from @iamruinous, however, the license allows you to fork, fix, and suggest the new repository to OMF's database.

We apologize for the inconvenience, but that's how deprecation goes...

**Comment by coderstephen** [comment]
Closing, since this is not an issue in OMF itself.
