### ISSUE TITLE
'init.fish' under $OMF_CONFIG is not honored anymore?

### ISSUE THREAD

**Issue by isnotnull** [oh-my-fish/oh-my-fish#328]
After using 'omf update' just now, the 'init.fish' under $OMF_CONFIG is not honored anymore.
I have to rename it to 'before.init.fish' to make it working.
Is this by design or anything else? The docutment doesn't say that.

Thanks.

**Comment by derekstavis** [comment]
Hmm, that's somewhat strange:

```
⋊> ~/.l/s/omf on master  cat $OMF_CONFIG/init.fish 
echo foobar
⋊> ~/.l/s/omf on master  omf reload
foobar
```

But if I do

```
⋊> ~/.l/s/omf on master  cat $OMF_CONFIG/init.fish 
set -x TEST_EXPORTED_VAR foobar
⋊> ~/.l/s/omf on master  omf reload
⋊> ~/.l/s/omf on master  echo $TEST_EXPORTED_VAR
```

It doesnt work. I need to

```
⋊> ~/.l/s/omf on master  cat $OMF_CONFIG/init.fish 
set -gx TEST_EXPORTED_VAR foobar
⋊> ~/.l/s/omf on master  omf reload
⋊> ~/.l/s/omf on master  echo $TEST_EXPORTED_VAR
foobar
```

**Comment by isnotnull** [comment]
Yes, you are right. 
I didn't notice that because I only have `set -x` in `init.fish`.
So strange behavior.

**Comment by derekstavis** [comment]
Yeah. In my case I'm not sure whether the change was related to current master or fish 2.3.0 upgrade

**Comment by isnotnull** [comment]
Another test with fish 2.2.0, it's the same.
```
➜ ~ fish -v
fish, version 2.2.0
```
```
➜ ~ cat $OMF_CONFIG/init.fish
set -x EDITOR 'vim'
echo 'test'
```
```
➜ ~ omf reload
test
➜ ~ echo $EDITOR

```

**Comment by derekstavis** [comment]
One possibility still remains: Recently the framework startup code changed entirely (see #260), touching the way package and user init files are collected, but it shouldn't influence how variable export works 😨

**Comment by coderstephen** [comment]
It is behaving like running in a subshell. @isnotnull are you using tmux or tmux-zen by chance?

**Comment by isnotnull** [comment]
@coderstephen , I'm not using tmux, just servers through `SSH`.

**Comment by nwykes** [comment]
I ran into this one tonight.  Updated OMF on one of my dev boxes where I use Webstorm for golang dev.  Webstorm was no longer seeing the GOPATH when launched from the shell (because it wasn't being set any longer).

This is on OS X, no ssh, no tmux, just running Fish as default shell in ITerm2

in init.fish:
`set -x GOPATH $HOME/gocode`

```
 ~  echo $GOPATH

```

change init.fish to:
`set -gx GOPATH $HOME/gocode`

```
 ~  echo $GOPATH                                                                      
/Users/nwykes/gocode

 ~  fish --version                                                                          
fish, version 2.3.0
```

**Comment by bobthecow** [comment]
Yeah, same setup. I had to change several things from `set -x` to `set -g`.

**Comment by coderstephen** [comment]
I can confirm that this is a regression. The problem lies in variable scope. Prior to #260, `$OMF_CONFIG/init.fish` was sourced inside `$OMF_PATH/init.fish`. Thus,

    set -x FOO

applied to the global scope. After the change, `$OMF_CONFIG/init.fish` is sourced via `require`, so the scope of the above statement applied to the `require` function scope, and not global scope. I am unsure how important this and how many people relied on this behavior in their config files. @derekstavis Can this be changed trivially in the init code?

**Comment by derekstavis** [comment]
@coderstephen, you are right about the why this behaviour is happening.

The way new init system works is by abusing of the [orthogonal] `require` function, which decrease startup code duplication, reduce the load time by using globs to generate valid paths with zero loops, and make the framework structure more homogeneous. Sourcing init hooks inside a function also brings `init.fish` a closed scope, making the init file not leak variables to global scope, which is cool but arise this issue.

The fix can be trivial if we are willing to duplicate some code, because to have the exported variables lay into the "global" scope we need to source the init paths in `$OMF_PATH/init.fish` file, but we still need to evaluate what is better for us, as this issue can be easily solved by using `set -gx` and could be easily documented.

[orthogonal]: http://fishshell.com/docs/2.3/design.html#ortho

**Comment by sagebind** [comment]
Let's accept this behavior since it seems reasonable to just use `-gx` and update the documentation to note this.
