### ISSUE TITLE
fish: An error occurred while redirecting file “/root/.config/omf/theme” open: Permission denied

### ISSUE THREAD

**Issue by Gabirel** [oh-my-fish/oh-my-fish#382]
OK, what I did are as followed:

1. install omf under root, and also `omf theme agnoster`
2. install omf under Buter  (Normal user) and also `omf theme agnoster`
3. `# su Buter`

It goes wrong!!!

It says: 
> fish: An error occurred while redirecting file “/root/.config/omf/theme”
open: Permission denied

Then, I do this: `# chmod 777 /root/.config/omf/theme` (Although it is stupid)

But, I get the same error message.

OK, Let me change the theme, I hope it goes bad because I choose agnoster unluckily. 

`omf theme batman`

SAME!!

I do this then: `omf doctor`
It says: 
> Your shell is ready to swim.

NEED TO PAY ATTENTIOIN:
        1. when you switch from `root` into `Buter`, it will tell you “`/root/.config/omf/theme`
        2. when you switch from `Daniel` into `Buter`, it will tell you `/home/Daniel/.config/omf/theme`
        3. I think it is the omf's fault, not my theme or fish shell

**Comment by oranja** [comment]
Hi @Gabirel,
Thanks for the report.

Now let's see. What happens if you use `su - Buter` instead?
(Notice the dash between `su` and `Buter`)

**Comment by derekstavis** [comment]
Just a quick explanation: `su -` clean current environment variables when spawning the shell under the new user. This is needed because it looks like the new shell under `Buter` is inheriting previous shell's `OMF_PATH` and `OMF_CONFIG` environment variables, used by Oh My Fish.

**Comment by Gabirel** [comment]
@oranja 
`su - Buter`, it shows:
> $ fish: Runtime path not available. Try deleting the directory
/tmp/fish.simpleJuCei and restarting fish.
Unable to make or open a FIFO for universal variables with path '.notifier': Permission denied

The shell itself shows no error message, except this(This is not your bug, it's mine,  I guess)

So, yes, as @derekstavis said, `su -` is ok.

But, could you guys fix this? I am a obsessive(a little).

**Comment by coderstephen** [comment]
@Gabirel I'm not sure how your user permissions are set up that causes `su - Buter` to not work (I just tried it out in a test environment and it works), but I believe that this command is the correct solution.

The fact that OMF configuration is inherited into subshells across users is intentional behavior. A very common use case is running `sudo -s`, which elevates a non-root user into a root shell. Many Fish themes take advantage of this situation by indicating that, while the user's current theme is still being used, the user currently is running as `root` instead. This allows the user to use their same theme and configuration in root and in normal shells.

If you do not want to inherit the previous user's configuration, `su -` is designed for that. In your case, since this command is not working, this might work instead (a little bit more wordy):

```fish
env -u OMF_CONFIG su Buter
```

The `-u` flag tells the `env` command to _unset_ a variable before executing the following command. This will cause the config path to _not_ be inherited by the subshell.

**Comment by Gabirel** [comment]
@coderstephen OH, This command works! Thanks
