### ISSUE TITLE
omf describe -- [mini-DoS]--> throttling/breakage

### ISSUE THREAD

**Issue by mobalt** [oh-my-fish/oh-my-fish#386]
Asking GitHub for a description of 76 packages and 63 themes (139 separate total requests) with no sleep in between qualifies as a Denial-of-Service attack, albeit tiny. It's no surprise then that I get the first ~15 descriptions very quickly, then each subsequent one takes an additional 1 sec, then 3secs (throttling), then nothingness: The last packages show a null description (#212). Running `omf describe` a second time at any point within the hour returns nothing but empty strings.

The code responsible for sending 139 curl requests in parallel is located at **omf.packages.describe.fish** 
Sure enough, running curl by hand I get the 403 response below. Apparently github caps the api at 60 requests per hour? Hence why the last packages have guaranteed empty description.
`{
  "message": "API rate limit exceeded for 95.96.97.98. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}`

Two possible fixes:
1) Create a repository that keeps a json or csv of all plugin/theme repo metadata (#358) . If worried about making sure user always has the latest metadata when running `omf describe`, then just have a git pull right before returning results. As far as I know, github doesn't throttle pull requests from unauthenticated users.

2) Keep your curl code, but aim it at a single resource containing data for all repos. e.g.,
**`curl -s`https://api.github.com/users/oh-my-fish/repos**

**Comment by coderstephen** [comment]
There was a lengthy discussion a while ago (albeit for a different reason) on a better way of packages storing metadata in a file in #196. Perhaps this should be visited again?

**Comment by oranja** [comment]
Thank you for starting this discussion, @Mobalt. This is an important issue in my opinion.
There is no doubt that abusing github's API is something we want to avoid.

We've been talking about creating a central repository, along with a friendly website, for some time now, but it always gets pushed back in favor of other core features.
So approach (2), even though it's already a huge improvement over what we have now, would not yield comprehensive results just yet. We can spare a good amount of calls with a single query of **oh-my-fish/repos**, and perhaps that will be the solution in the short term, but it doesn't scale as long as we allow repositories outside of the *oh-my-fish* organization.
One little thing more: Parsing the JSON response of the **/repos** API call would either introduce a third-party dependency (such as [`jq`](https://stedolan.github.io/jq/)), or a `fish`-y solution. A solution in fish might turn out just fine, but you know how it usually goes: More code = more bugs. Tricks and hacks = shorter code with probably the same amount of bugs.

As for (1), as @coderstephen said, keeping some form of mostly-static metadata has been discussed in the past. I think there is a an advantage to your suggestion of a single file with data for the entire database, since most of the time `omf describe` is desired for packages in the database which are not yet installed locally, while in the original proposal for metadata files, you'd only get descriptions for packages which are already installed. That's unless you fetch data from raw/master, and then it's not much different from calling the API 139 times in succession (or is it?). The disadvantages I see in your approach are the duplicity of data and hence the need to keep the data in sync.

Loosely related anecdote:
At one point I had a suggestion to keep track of changes in packages in a central location - a background worker on a server would issue pull requests or API calls and update a static resource with a timestamp. That would help avoid the need of every user to to create a new `git pull` connection for each package (currently an annoying bottleneck for updates). I realize now that besides becoming a single point of failure, it also suffers from a similar issue of scaling when talking about packages outside OMF's package database.

If you ask for the bottom line, I think that we should start with minimizing the abuse of GH's API, probably with the suggestion in (2), and then try to move towards (1) with some automatic process (either with a cron job on some server or by some trigger, perhaps hijack Travis) that queries repository links from the package database for status (maybe the repository is removed?) and description and saves the result into a central db metadata file. We should keep in mind that the website will want to have the same data about db packages.

**Comment by Mobalt** [comment]
Why not just package everything + the kitchen sink into the master repo via `git submodule` or `git subtree`? 

1. Rather than installing/removing, the user would enable/disable packages possibly through symlinks or whitelists.
2. 3rd-part plugins can be installed/managed by a thin wrapper around `git submodule init/deinit` 
3. git is really good at managing changes, rather than implementing a hacky timestamp checker, updates would be done via `git submodule update "package"` or for universal update `git pull --recurse-submodules`
4. Bonus:  The main oh-my-fish repo can quality control submodules before passing exposing them to the users. So currently omf blindly downloads the latest plugin located at https://github.com/.../plugin.git, but with submodules, the main repo could now be able to specify a specific hash commit to prevent bad actors from making the latest commit be something nasty.

Also, having these as submodules one could write a script that goes through each submodule and concatenates the contents of the README files. Then whenever there's an update, just rerun the script and a new index.md file would be created containing a directory of all plugins and what they do in beautiful md/html..possibly with pictures, screenshots, free coffee and the cure to cancer. Okay, maybe I'm getting carried away with my feature requests.

**Comment by oranja** [comment]
Hold on. We can discuss all of these ideas, but for most of them I don't see how they're supposed to solve the `describe` issue.

Anyway:

1. We already have a [script](/oh-my-fish/oh-my-fish/blob/master/tools/generate-themes-doc.fish) that concats theme READMEs. Frankly it hasn't been run in a long while due to issues with Travis and humans being forgetful. Here's the latest [Themes.md](/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md).
It's possible to do the same for package repository descriptions, but you'll still use the API for this, so you have to focus on the API abuse issue. One way to increase the limit is to register the script as an app, though it's not free...

2. I think that the problem with submodules is that we're trying to go the opposite way: The ambition is to decouple the packages from the package manager. I admit that I haven't worked with submodules yet, but I fear that by letting `git` manage the packages, it becomes problematic for the core contributors to work without overwriting each others' bundle state (which packages are installed). Note how OMF currently saves the bundle and theme configuration in a separate (not git managed) folder.

3. (4) I'm not sure we have the manpower to audit every package on each update. You're right in your concern, but for now the security model is more or less: "User wants to contribute => user probably have no evil intentions". You're free to open an issue for this so it will be given serious thought.

**Comment by sagebind** [comment]
This will be solved as part of #427.

**Comment by sagebind** [comment]
#427 is merged and `omf describe` no longer makes network requests to GitHub. Closing as solved.
