### ISSUE TITLE
Local theme created using scaffold can not be used with `omf install <localtheme>`

### ISSUE THREAD

**Issue by lachenmayer** [oh-my-fish/oh-my-fish#401]
Hiya, installing fish on a new laptop, shows me how outdated all my dotfiles are on my old machine ;)

To reproduce:

```
omf new theme foobar
omf install foobar
```

expected: new theme is used
actual: 

```
fatal: repository 'foobar' does not exist
Could not install package foobar.
```

<img width="412" alt="screen shot 2016-09-12 at 17 52 43" src="https://cloud.githubusercontent.com/assets/38614/18444582/bf617a4c-7911-11e6-9caf-cb4b57b13660.png">

Manually editing the `theme` file **does** work as expected.

macOS 10.11.6 / fish 2.3.1 / omf 2

**Comment by oranja** [comment]
I'm a little confused by these instructions.
Did OMF ever support installing a local package just by name? My guess would be "no".
As far as I can recall, you always need some git repository to point at. And while you can technically create a URL for a local git repository, the instructions here don't even point you in the right direction.

Offline package/theme install is something we need to get on top of. Feel free to suggest a PR.

**Comment by lachenmayer** [comment]
I don't know, the last version of oh-my-fish I've used is clearly the
"legacy" version. In that, I recall manually sourcing all the relevant
fish_prompt/etc files manually.
Will take a closer look at this later this week - there shouldn't be any
need to create a git repo, it works just fine when I manually edit the
"theme" file.
Thanks for taking a look.

**Comment by fredo-wunder** [comment]
Hello! 
Same problem here... and it would also be cool to have a way of forking existing themes and be able to then install the fork. Could you guide me there? ;)

thanks!

**Comment by oranja** [comment]
@lachenmayer: Any news?

@fredo-wunder: What you're asking is very doable. The basic steps are:

1. Find the theme's repository URL:
`cat $OMF_PATH/db/themes/<name_of_the_theme>`
(replace `<name_of_the_theme>` with the name of the theme that you want to fork)

2. Go to this URL in your browser and click on _Fork_ in the upper right corner.
Alternatively, you can just add `/fork` to the end of the address bar and press Enter.
I recommend that you rename the repository (but keep the **theme-** prefix) so that you don't have conflicts.

3. Now that you have a fork of the repository on your github account, you can clone it to your computer to work locally.
`git clone https://github.com/fredo-wunder/<name_of_the_theme>`

4. Make changes, add files, commit, push. Do your magic. :star2:

5. Install your theme with `omf install https://github.com/fredo-wunder/<name_of_the_theme>`.

If you make additional changes to your theme, you can simply update OMF (`omf update` / `omf u`). You can also selectively update just your theme with `omf u <name_of_the_theme>`.

If you have more questions, feel free to ask.

**Comment by sagebind** [comment]
The questions seem to be answered. `omf install` is currently designed for installing packages in the database, not package directories around the filesystem.

**Comment by jdob** [comment]
I'm not sure I'd personally consider this closed, since the instructions given by omf itself are misleading. I created a new theme following what's in README.md and see the same as the original poster:

> ~/.c/omf omf new theme jdob                                                                                                                                                     15:06:23
 create  fish_greeting.fish
 create  fish_prompt.fish
 create  fish_right_prompt.fish
 create  fish_title.fish
 create  LICENSE
 create  README.md
Switched to /Users/jdob/.config/omf/themes/jdob
Theme not installed!
Install it using omf install jdob

omf is telling me to use "omf install" to install the theme, but when I try that, I see this issue.

⋊> ~/.c/o/t/jdob omf install jdob                                                                                                                                                  15:06:48
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package jdob
fatal: repository 'jdob' does not exist
Could not install jdob.

**Comment by sagebind** [comment]
@jdob The instructions are not misleading, but there is a bug in the code. I thought we fixed that at some point, but it seems I was just imagining it. The problem is that `omf new theme <whatever>` tries to set the theme after, which cannot be done. See https://github.com/oh-my-fish/oh-my-fish/issues/375#issuecomment-283064420

This issue is closed because the problem you are describing is a different issue.

**Comment by sagebind** [comment]
@jdob I created a new issue specifically for the problem you see. #529

**Comment by jdob** [comment]
Ahh, ok, my bad. I thought the resolution was that it wasn't a bug. Thanks for the clarification :)
