### ISSUE TITLE
Packages name clashing 

### ISSUE THREAD

**Issue by rominf** [oh-my-fish/oh-my-fish#404]
I wanted to use https://github.com/oh-my-fish/plugin-gi. I ran:

```
omf install gi
```

But it installed https://github.com/fishery/gi.

I think guidelines how to handle this are needed.

**Comment by sagebind** [comment]
@rominf Interesting. I would have expected `gi` to refer to https://github.com/oh-my-fish/plugin-gi as well, since it is in the official repository. This seems to be an index mistake.

Until the index is updated, you can install `gi` like this:

```fish
omf install https://github.com/oh-my-fish/plugin-gi
```

@oh-my-fish/core Should we have a policy for name clashing in the database? Here the official `plugin-gi` should get the `gi` name, but we may not have such clear-cut conflicts in the future.

**Comment by sagebind** [comment]
I think the best solution here to keep it simple is to address naming conflicts individually. Plugins can always be renamed in the package database if an issue arises.
