### ISSUE TITLE
Color changes

### ISSUE THREAD

**Issue by denningsrogue** [oh-my-fish/oh-my-fish#455]
I just migrated from an old MacBook Pro to a new one.  I use the godfather theme, but now the colours have changed.  The prompt is the same but the commands have changed from dark blue to white and the paths have changed from light blue to turquoise.  Many other colours have changed as well. Any ideas why and how to change it back?

**Comment by oranja** [comment]
Two things to check:

1. In whatever terminal app you use (usually Terminal.app or iTerm2 for Mac), check the configuration and see if your color theme affects how the colors are displayed in your terminal window.
2. Inside the shell, run `fish_config`. A browser window will open and you will see fish's configuration interface. You can choose from a few color themes there and you can also customize the colors so they fit your taste.

Since the **godfather** theme uses basic color names (e.g.: `cyan`, `red`, etc.) and not special named colors (e.g.: `$fish_color_command`), I tend to believe that you will find a solution in (1).

If this doesn't resolve your issue come back and we'll do some more digging.

**Comment by denningsrogue** [comment]
Thank you Itzik.  I started down that path and found that running fish_config helped resolved some of the issues (highlighted green text is still a problem).  I really appreciate your help.

-- 
Richard Peters
richardpeters@me.com
