### ISSUE TITLE
Cannot found the pyenv plugin.

### ISSUE THREAD

**Issue by otsukaresama** [oh-my-fish/oh-my-fish#463]
I can get access to the plugin-pyenv page under the on-my-fish project, however, couldn't install it by the "omf install" command. It seemed to be not in the package list any more.

**Comment by oranja** [comment]
Hi @otsukaresama,
What exactly did you try?

If you haven't done so in a long time, try to update OMF.
Then you should be able to install `pyenv` without an issue.
```fish
> omf update
...
> omf install pyenv
Installing package pyenv
✔ package pyenv successfully installed.
```


_Tips:_

1) Notice that omf-related git repository names have prefixes, like `omf-plugin-`/`plugin-` and `omf-theme-`/`theme-`, which are not part of the package's name. This convention helps OMF figure out what type of a package it is handling. Drop the prefix when you're installing a package with OMF.

2) Run `omf list --available --plugin` to see the names of plugins that you can install.

**Comment by otsukaresama** [comment]
@oranja Thank you for your reply. I installed oh-my-fish just in order to get pyenv support. So after the installation four days ago, It had already been up to date(Absolutely I also ran the `omf update`). Here is the list of packages after I ran `omf list --available --plugin`

```
baoruiqi@chi ~> omf list --available --plugin                                     12:57:13
android-sdk			license
ansible				linuxbrew
apt				local-config
archlinux			mix
argu				mou
artisan				mvn
await				node-binpath
aws				nodenv
balias				nvm
bang-bang			osx
basename-compat			pbcopy
battery				peco
bundler				php-version
cd				phpbrew
composer			powerline
config				proxy
direnv				rails
docker-machine			rbenv
emacs				rustup
errno				rvm
exenv				spark
expand				ssh-config.d
export				ssh-term-helper
extract				sublime
fasd				sudope
fonts				tab
foreign-env			technicolor
fzf				termux
gem				thefuck
getopts				tiny
gi				title
git-flow			tmux-zen
gityaw				vcs
grc				vi-mode
hash				virtualfish
homebrew-command-not-found	vundle
hub				wd
iex				weather
jump				wifi-password
keychain			wttr
kill-on-port			z
```

**Comment by oranja** [comment]
Ohhh... I see what happened.
You are running the 'stable', version 3 of OMF (you can verify with `omf channel`). This means that updates only go from release to release (git tags), and don't pull the commits in between, until the next release.
Since `pyenv` was added to the registry after the v3 tag, your local copy of OMF doesn't recognize it.

If you want to always get the latest updates with `omf update`, and don't mind the possible instability, you can go ahead and switch to the 'dev' channel:
```fish
> omf channel dev
> omf update
```
Then you will able to `omf install pyenv`.

If you prefer to stay on the 'stable' channel, you can still install the pyenv plugin, by providing the full URL:
```fish
> omf install https://github.com/oh-my-fish/plugin-pyenv
```


@oh-my-fish this serves as a reminder to go ahead and separate the db/registry from the main repository.
I suppose that only rarely will a package need to be restricted to a specific OMF version. More likely it will have issues with fish. Both of these cases can be solved with the near-future metadata system.

**Comment by otsukaresama** [comment]
Thank you very much!
