### ISSUE TITLE
how to remove [I]

### ISSUE THREAD

**Issue by qcdong2016** [oh-my-fish/oh-my-fish#497]
![image](https://cloud.githubusercontent.com/assets/6292878/23647789/a5459910-0352-11e7-95d8-fe71cf2112de.png)

**Comment by bobthecow** [comment]
That [I] is a built-in fish indication that you're in vi "insert mode". If this isn't intentional, you can call `fish_default_key_bindings` to go back to normal. If you _are_ intentionally using insert mode, and just want to remove the indicator, you can do that by overriding `fish_mode_prompt`. For example, this will disable all mode prompts entirely:

```
function fish_mode_prompt; end
```

… or something like this will let you show the mode prompt only when it's not insert mode:

```
function fish_mode_prompt
  switch $fish_bind_mode
    case insert
      # do nothing
    case '*'
      fish_default_mode_prompt
  end
end
```
