### ISSUE TITLE
"Please install z first!"

### ISSUE THREAD

**Issue by mathpunk** [oh-my-fish/oh-my-fish#511]
Someone suggested I try 'z'. On Arch Linux, I installed z-1.9-1 from AUR, then ran `omf install z`, and got, "Please install 'z' first!"

Is this a problem with the AUR package, omf, or is something wrong with my local environment?

**Comment by sagebind** [comment]
My guess is you did not set `$Z_SCRIPT_PATH` correctly. See [the README for the `z` plugin](https://github.com/oh-my-fish/plugin-z):

> In order to use z, it's necessary to specify the script file path. You can do so by adding the following snippet to your ~/.config/fish/config.fish file before sourcing Oh My Fish.
>
>     set -g Z_SCRIPT_PATH <PATH_TO_Z_SCRIPT_FILE>

I'm questioning whether that's a good setup experience for the plugin; if you like maybe you could create an issue on the plugin repo so that the plugin author will see it.

**Comment by mathpunk** [comment]
Thanks, that's exactly what happened because I read a blog post instead of the documentation.
