### ISSUE TITLE
new / updated keychain package

### ISSUE THREAD

**Issue by jitakirin** [oh-my-fish/oh-my-fish#531]
Hiya, I updated the [keychain](http://www.funtoo.org/Keychain) package for fish [here](https://github.com/jitakirin/pkg-keychain) to work with OMF and was hoping to move it into the OMF organisation. Would that be possible?

**Comment by oranja** [comment]
Hey @jitakirin,
Sorry for the long delay.

I advise that you resubmit this package to [oh-my-fish/packages-main](https://github.com/oh-my-fish/packages-main).
While you do so, it would help if you'll explain the key differences between your implementation and the current one from [fishgretel/pkg-keychain](https://github.com/fishgretel/pkg-keychain). I can see that your code is clean and concise, but the current version sends some arguments to `keychain` that I, and whoever else reviews your request, would like to understand better - namely `confhost` and `timeout`. Mainly to understand if the average user will benefit more from keeping these arguments or discarding them. (I never used `keychain`).

**Comment by jitakirin** [comment]
@oranja I was thinking about moving it into the organization first and was going to submit to the index after as I wanted it to be possible for other people to co-maintain the package if needed, but I don't mind, I can submit to the index first

**Comment by oranja** [comment]
I see what you're saying. Yet, a decision was made to put all core dev in one repo and all pacakge related talk in `pacakges-main` (or other alternative repositories). It's just a technicality, and either way, that's not the real issue here in my opinion.

As I said, I think you should address the conflict between the older `keychain` and your `keychain` plugin. What do users gain and what do they lose by getting your plugin over the current one?

**Comment by jitakirin** [comment]
@oranja oh yeah, totally understand, will prep a PR

**Comment by sagebind** [comment]
Closing as discussion moved to https://github.com/oh-my-fish/packages-main/pull/21.
