### ISSUE TITLE
AAAA record points to link-local address

### ISSUE THREAD

**Issue by n3vu0r** [oh-my-fish/oh-my-fish#551]
This breaks `curl -L https://get.oh-my.fish | fish` for IPv6-only networks using DNS64.

**Comment by oranja** [comment]
Hi @n3vu0r,

You're right. I was just too blindly optimistic when I set up the AAAA record and missed the meaning of the `FE80:` subnet.
I asked the server provider to allocate an external IPv6 address, and in the meantime removed the misleading AAAA records to get out of the way of DNS64.

Thanks for reporting this!

**Comment by n3vu0r** [comment]
Thank you, that was quick. It works now!

**Comment by oranja** [comment]
Hello again @n3vu0r,

I've been working with our VPS provider over the last few days to get a global IPv6 address dedicated to the VPS. Will it provide any value if we point the AAAA records there? Or is DNS64 good enough for all intents and purposes?

P.S.
Turns out that LeaseWeb are not the most professional VPS providers, at least when it comes to handling their low-tier customers. Might be worth considering when looking for infrastructure solutions for production environments.

**Comment by n3vu0r** [comment]
Hi @oranja,

having an AAAA record with valid global IPv6 address is always nice to have. It would mean, oh-my-fish is IPv6-ready and future-proof... and so on :) But for now and the next years, nobody will notice a difference, every IPv6-only network will have some kind of IPv6 to IPv4 translation because most of the Internet is still IPv4-only. This translation is transparent, it shouldn't have any disadvantages. In case you succeed with LeaseWeb to get an IPv6 address, the web server on the VPS must be configured to listen to IPv6 addresses as well. If it's too time consuming to get IPv6 working with this provider, that's totally fine.

**Comment by oranja** [comment]
Both IPv6 and IPv4 should work natively now, except that the final destination - raw.githubusercontent.com - doesn't feature an IPv6 stack.
Let me know if it brings any new issues.

**Comment by n3vu0r** [comment]
Nice, works fine. Native IPv6 now for get.oh-my.fish and then DNS64 for raw.githubusercontent.com:

```text
$ curl -vL https://get.oh-my.fish/
...
* Connected to get.oh-my.fish (2001:1af8:4700:a400:11::2) port 443 (#0)
...
* Connected to raw.githubusercontent.com (64:ff9b::9765:85) port 443 (#1)
...
```
