### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by Deathlive** [oh-my-fish/oh-my-fish#557]
"errbuf != NULL " failed

![default](https://user-images.githubusercontent.com/29791715/30743313-1d4a4b48-9fae-11e7-879b-dacbb628e848.png)

**Comment by oranja** [comment]
Hi @Deathlive,
Please take the time to add a little bit more information on the environment in which this error occurs.
Especially when you're running fish and OMF in an unconventional environment.

A preliminary investigation indicates that this problem is related to Termux and Android's standard C library implementation, called Bionic.
According to https://github.com/termux/termux-packages/issues/877, I recommend that you try to upgrade all of the installed packages in Termux (`pkg up`).
If that doesn't solve the error, you might have to upgrade to Android 7.0 or later.

**Comment by Deathlive** [comment]
@oranja thanks, understandably)
