### ISSUE TITLE
Install omf on mac

### ISSUE THREAD

**Issue by RoraxHan** [oh-my-fish/oh-my-fish#590]
![screen shot 2018-01-23 at 2 55 05 am](https://user-images.githubusercontent.com/25556402/35238675-0cc017b6-ff63-11e7-86de-73422d7f7585.png)

When I try to this command 
`curl -L https://get.oh-my.fish | fish
`
I'm getting error like above image.

**Comment by bobthecow** [comment]
You have a file called `HEAD` in XAMPP's bin directory, and it's earlier in your `$PATH` than `/usr/bin/head`. To fix this, you can do one of the following:

* remove the XAMPP bin directory from your path
* put it at the end, so the system default `head` will win
* remove that file, because I can't imagine it's useful

**Comment by RoraxHan** [comment]
Currently Xampp path is at the end in the bash_profile.
If I remove the HEAD fiel from the xampp bin folder, that doesn't affect for running php server?

**Comment by bobthecow** [comment]
If it's at the end, it shouldn't take precedence over the builtin head. You can `echo $PATH` to see the list in order.

I haven't used `*AMP` in years, so I can't say for certain, but I doubt an all-caps `HEAD` is meant to be the `head` executable. Probably more likely an artifact of version control or something? 

If you're worried, rename it to `HEAD.bak` rather than deleting it. Then you can put it back if something breaks :)

**Comment by RoraxHan** [comment]
Yes. I did like that.
After install the omf, can I get back the file name as origin?

**Comment by bobthecow** [comment]
I wouldn't recommend it. Anything on your system trying to use `head` will get that one instead, and it is almost certainly not what things need. What is that file? What happens if you run it?

**Comment by RoraxHan** [comment]
I don't know what is that file exactly.
Anyway, I've install omf now. and thanks for your support.

**Comment by sagebind** [comment]
_Unrelated_: @bobthecow The new installer checks are _so_ handy for debugging these kinds of install issues!

**Comment by bobthecow** [comment]
Yes. Yes it does :)
