### ISSUE TITLE
Changing to Git directories takes a long time

### ISSUE THREAD

**Issue by BuZZ-dEE** [oh-my-fish/oh-my-fish#624]
Changing to Git directories takes long if the repository (2,1 GB) is big.

**Comment by caixiangyue** [comment]
me too.

**Comment by sagebind** [comment]
What platforms is this occurring on? On Windows it is a known problem, where Git itself is very slow on Windows in some configurations: #598

**Comment by caixiangyue** [comment]
Xubuntu 18.04. My git repository is very large(about millions of files).But I only execute the command in the main directory of the git repository and there will be obvious slow

**Comment by bobthecow** [comment]
I have similar problems with my work repo 😞

I’d suggest checking out bobthefish. It gives you lots of levers to speed up git integration without disabling it completely. 

Start by setting `bash.showDirtyState` and/or `bash.showUntrackedFiles` in git config for the repo in question. In my case, those were enough to make it tolerable, and still have the benefits of things like branch name, stash status, etc. in my prompt. 

If those don’t make it fast enough, you can add your repo to `theme_vcs_ignore_paths` and it’ll disable git integration for just that repo.

**Comment by faho** [comment]
>Well the default theme invokes git several times in order to populate the branch name, dirty status, etc, every time the prompt is drawn.

@sagebind: It actually invokes git a few more times than necessary, but the main issue as reported by @hrvoj3e in https://github.com/fish-shell/fish-shell/issues/5185 appears to be `git status --porcelain`. That is actually one of the git calls that does the most, because the idea is to do _everything_ in one git call. I think you could implement a complete prompt with it (if you got to use the v2 format, because that can also print the branch and ahead/behind info).

Only this uses it in [git_is_touched](https://github.com/oh-my-fish/oh-my-fish/blob/master/lib/git/git_is_touched.fish), where it just checks if it has any output and throws it away.

In upstream fish, we use `git diff --no-ext-diff --quiet` to determine if the repo is "dirty" (official git parlance).

Those who have slow git repos: Can you try that one instead to see how it behaves?

**Comment by Pobega** [comment]
@faho I work with the Chromium git repo which is notoriously bad with these types of things (https://chromium.googlesource.com/chromium/src/)

My prompt takes about 1.5 seconds so who up in this repo. As for the performance, `git status --porcelain` in this repo takes 0.787s while `git diff --no-ext-diff --quiet` takes 0.084s

**Comment by derekstavis** [comment]
@Pobega Would you ming trying to use my fork of the default theme to see if it improves the performance for you?

The steps to do it are:

```sh
omf cd default
git remote rm origin
git remote add origin http://github.com/derekstavis/theme-default
git fetch
omf i technicolor vcs
git reset --hard origin/master
omf reload
```

This fork uses the `vcs` package to detect and render the git prompt. It also has a directory cache, meaning that subsequent prompt renders on the same directory are instant. You might still get the performance penalty when you change the directory though.

**Comment by skalle** [comment]
Tried your fork @derekstavis .. Still slow for me, rendering the prompt take pretty much the same amount of time as with `bobthefish`

**Comment by faho** [comment]
@derekstavis: That does `vcs.touched`, which in https://github.com/oh-my-fish/plugin-vcs/blob/master/functions/git/vcs.touched.fish also does `git status --porcelain` _just to check if there is output_.

That's one of the most expensive `git` calls you could do, and you're not even using what it provides. 

Something like `command git diff --no-ext-diff --quiet --exit-code 2>/dev/null` is going to be _much_ quicker, and provides the same information (in my qt5 clone it's 500ms vs 110ms hot-cache).

**Comment by derekstavis** [comment]
@faho I tested and really it makes a big difference in speed. The main problem now is that this command doesn't report "touched" when there are things on stage to be committed. Do you know any other means to keep this behavior?

**Comment by faho** [comment]
@derekstavis: Our git-prompt uses `not command git diff-index --cached --quiet HEAD -- 2>/dev/null`. Which is quite fast, since all it needs to do is check the staging area (or "cache" or "index", because git really can't decide what to name the thing).

The `not` is because `diff-index` returns 1 if there *is* a diff, but we wanted to return 0 (i.e. true) in that case.
