### ISSUE TITLE
How do I change the theme manually

### ISSUE THREAD

**Issue by carc1n0gen** [oh-my-fish/oh-my-fish#632]
How does one change the theme manually after installing a theme broke the shell so bad the omf command doesn't work? I literally can't use fish right now.

**Comment by asfaltboy** [comment]
Try changing the file contents here: `~/.config/omf/theme`

To e.g `default`

**Comment by carc1n0gen** [comment]
This was the first thing I tried, with no luck

**Comment by comfortablynick** [comment]
I would like to know this too. I _really_ would like to be able to change the theme with an environment variable. As it is now, I keep my config in git and every time I change the theme with OMF, several files are edited, moved or linked. The symlinks that OMF creates also are different depending on the OS. I've had all sorts of issues with themes...

**Comment by derekstavis** [comment]
I agree that the symlink was a bad idea of mine. It's cool tho because it has integration with `fish_config` utility. Maybe it's time to drop this as it's more a source of confusion than of help.

About your specific intention, unfortunately there's no way to control the current theme using a variable, but a variable override should be fairly easy to implement.
